name: Run Coverage

on:
  push:
    branches:
    - main
    - tests/running

jobs:
  build-node-template:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

      - name: Install Rustup
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source ~/.cargo/env
          rustup default stable
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly
      - name: Run coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.19.1'
          args: '-- --test-threads 1 --manifest-path ./pallets/fiat-ramps/Cargo.toml'
      
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
